### ISSUE TITLE
`ValueError: Failed to find a callable in <NULL>` on dill.dumps(GeneratorType)

### ISSUE THREAD

**Issue by creatorrr** [pulkin/pyteleport#1]
Code to reproduce:
```python
import pyteleport as pt, dill as d

def gf():
    yield 1
    yield 2

d.dumps(gf())
```

Stacktrace:
```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/diwank/.local/lib/python3.10/site-packages/dill/_dill.py", line 263, in dumps
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
  File "/home/diwank/.local/lib/python3.10/site-packages/dill/_dill.py", line 235, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/home/diwank/.local/lib/python3.10/site-packages/dill/_dill.py", line 394, in dump
    StockPickler.dump(self, obj)
  File "/home/diwank/.asdf/installs/python/3.10.5/lib/python3.10/pickle.py", line 487, in dump
    self.save(obj)
  File "/home/diwank/.local/lib/python3.10/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/home/diwank/.asdf/installs/python/3.10.5/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/diwank/.local/lib/python3.10/site-packages/pyteleport/dill_tools.py", line 39, in pickle_generator
    morph_fun = morph_stack(snapshot(obj.gi_frame, stack_method="direct"), root=False, flags=0x20)
  File "/home/diwank/.local/lib/python3.10/site-packages/pyteleport/snapshot.py", line 241, in snapshot
    raise ValueError(f"Failed to find a callable in {vstack[stack_size]}")
ValueError: Failed to find a callable in <NULL>
```

**Comment by pulkin** [comment]
Thanks for pointing this
